version: "3.8"

services:
  web:
    build: .
    container_name: ai_call_assistant
    ports:
      - "8007:8000"
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
