version: "3.8"

services:
  web:
    build: .
    container_name: ai_call_assistant
    ports:
      - "8010:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo

  # Redis service
  redis-server:
    image: redis:latest
    container_name: redis-law_firm_crm-server
    ports:
      - "6370:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}  # Load password from .env file
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]  # Use the password from the environment variable
    volumes:
      - redis_data:/data
    restart: always

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db

volumes:
  redis_data:
  mongo_data:
    driver: local
